# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt-get install qemu-user-static debootstrap

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          #   Root folder on your system for the new 'chroot' build environment
          export CROSS_ROOT_DIR=~/build-envs/armhf
          #   Target CPU architecture (E.G 'armhf' or 'arm64')
          export CROSS_ARCH=armhf
          #   Which version of Debian the target version of Raspbian is based on (E.G: 'bullseye', 'buster', 'stretch' etc.)
          export CROSS_DEBIAN_VER=buster
          mkdir -p "${CROSS_ROOT_DIR}"
          #sudo mount -i -o remount,exec,dev /home/runner
          sudo debootstrap --no-check-gpg --foreign --arch=${CROSS_ARCH} ${CROSS_DEBIAN_VER} "${CROSS_ROOT_DIR}" http://archive.raspbian.org/raspbian
